version: '3'

services:
  mongodb:
    image: 'mongo'
    container_name: 'coc_mongo'
    environment:
      - MONGO_INITDB_DATABASE=call_of_cthulhu
      - MONGO_INITDB_ROOT_USERNAME=vitor
      - MONGO_INITDB_ROOT_PASSWORD=pepperonipizza
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - '27018:27017'